# BERT

issue with word2vec :

fixed embedding: meaning of some words are different in 2 sentences

BERT can generate contextualized embeddings.

it can look at the contex of the statement and generate feature base on that

it can also generate embedding for entire sentence

there are 2 versions of BERT: BERT base (12 encoder layer) and BERT large (24 encoder layer)

trained on 2500 M word on wikipedia and 800 M words on books,etc

BERT stands for : bidirectional encoder representations from transformers

# code

In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
preprocess_url = "https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-preprocess/3"
encoder_url = "https://www.kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-l-12-h-768-a-12/4"

In [4]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [5]:
text_test = ['nice movie indeed', 'i love data science']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [6]:
bert_model = hub.KerasLayer(encoder_url) # it will generate word embedding model
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['default', 'pooled_output', 'sequence_output', 'encoder_outputs'])

In [7]:
bert_results['pooled_output'] # is embedding vector for entire sentence

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177463, -0.21411951,  0.49769327, ...,  0.24465072,
        -0.47334516,  0.81758744],
       [-0.7441596 , -0.15070038,  0.542165  , ...,  0.2885735 ,
        -0.5054263 ,  0.7955121 ]], dtype=float32)>

In [8]:
bert_results['sequence_output'] # is individual embedding vectors

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292038,  0.08567842,  0.14476822, ..., -0.09677143,
          0.08722145,  0.07711081],
        [ 0.17839344, -0.19006258,  0.5034949 , ..., -0.0586981 ,
          0.32717144, -0.15578583],
        [ 0.18701449, -0.43388814, -0.48875296, ..., -0.15502766,
          0.00145172, -0.2447103 ],
        ...,
        [ 0.12083013,  0.12884311,  0.4645362 , ...,  0.07375546,
          0.17441897,  0.16522236],
        [ 0.07967884, -0.01190644,  0.5022541 , ...,  0.13777748,
          0.210022  ,  0.00624548],
        [-0.07212698, -0.28303394,  0.5903344 , ...,  0.4755187 ,
          0.1666846 , -0.08920381]],

       [[ 0.17763807,  0.15645882,  0.09271723, ..., -0.08026289,
          0.13287097,  0.23332372],
        [ 0.64550316,  0.08793751, -0.20939505, ..., -0.22275954,
          0.78166217,  0.45110697],
        [ 1.2851384 ,  0.78914374,  0.25609958, ...,  0.11022428,
          0.6739603 ,  0.23330894],
        ...,

In [10]:
len(bert_results['encoder_outputs']) # its 12 because we are using bert with 12 encoder layer

12

In [11]:
bert_results['encoder_outputs'][-1] # last layer's output is same as sequence output

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292038,  0.08567842,  0.14476822, ..., -0.09677143,
          0.08722145,  0.07711081],
        [ 0.17839344, -0.19006258,  0.5034949 , ..., -0.0586981 ,
          0.32717144, -0.15578583],
        [ 0.18701449, -0.43388814, -0.48875296, ..., -0.15502766,
          0.00145172, -0.2447103 ],
        ...,
        [ 0.12083013,  0.12884311,  0.4645362 , ...,  0.07375546,
          0.17441897,  0.16522236],
        [ 0.07967884, -0.01190644,  0.5022541 , ...,  0.13777748,
          0.210022  ,  0.00624548],
        [-0.07212698, -0.28303394,  0.5903344 , ...,  0.4755187 ,
          0.1666846 , -0.08920381]],

       [[ 0.17763807,  0.15645882,  0.09271723, ..., -0.08026289,
          0.13287097,  0.23332372],
        [ 0.64550316,  0.08793751, -0.20939505, ..., -0.22275954,
          0.78166217,  0.45110697],
        [ 1.2851384 ,  0.78914374,  0.25609958, ...,  0.11022428,
          0.6739603 ,  0.23330894],
        ...,